{% set version = "0.13.6" %}

package:
  name: scp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scp/scp-{{ version }}.tar.gz
  sha256: 0a72f9d782e968b09b114d5607f96b1f16fe9942857afb355399edd55372fcf1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - paramiko

test:
  imports:
    - scp

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
