{% set version = "0.13.2" %}

package:
  name: scp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scp/scp-{{ version }}.tar.gz
  sha256: ef9d6e67c0331485d3db146bf9ee9baff8a48f3eb0e6c08276a8584b13bf34b3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - paramiko

test:
  imports:
    - scp

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
