{% set name = "scp" %}
{% set version = "0.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scp-{{ version }}.tar.gz
  sha256: 64f0015899b3d212cb8088e7d40ebaf0686889ff0e243d5c1242efe8b50f053e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - paramiko

test:
  imports:
    - scp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
