{% set version = "0.13.4" %}

package:
  name: scp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scp/scp-{{ version }}.tar.gz
  sha256: e60948dd3e1aa13da21aa1bf8a025fabbbc2816ed04f1a1272410247d1a86f15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - paramiko

test:
  imports:
    - scp

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
