schema_version: 1

context:
  version: "0.16.2"

package:
  name: scp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/scp/scp-${{ version }}.tar.gz
  sha256: d049f9aa77db4042c44b922cecabe97ef0716fb334a95701d68d1c7991684fc2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - paramiko

tests:
  - python:
      imports:
        - scp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: scp module for paramiko
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  homepage: https://github.com/jbardin/scp.py

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
